# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wabousfi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/28 00:34:13 by wabousfi          #+#    #+#              #
#    Updated: 2018/02/28 00:34:15 by wabousfi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ex09

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -Iincludes sources/*.c -o ft_advanced_do-op

clean:
	/bin/rm -f ft_advanced_do-op
